# Generated by Django 5.2 on 2025-04-28 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_networkedge'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='networkedge',
            unique_together={('from_user', 'to_user')},
        ),
    ]
